package com.kgaft.VulkanContext.Vulkan.VulkanRenderPass;

import com.kgaft.VulkanContext.Exceptions.BuilderNotPopulatedException;
import com.kgaft.VulkanContext.Vulkan.VulkanImage.VulkanImage;

import java.util.List;

public class VulkanRenderPassBuilder {
    private int imagePerStepAmount = 0;
    private boolean autoGenerateDepthImages = false;
    private List<VulkanImage> colorAttachments;
    private List<VulkanImage> depthAttachments;

    public VulkanRenderPassBuilder() {
    }

    public int getImagePerStepAmount() {
        return imagePerStepAmount;
    }

    public void setImagePerStepAmount(int imagePerStepAmount) {
        this.imagePerStepAmount = imagePerStepAmount;
    }

    public boolean isAutoGenerateDepthImages() {
        return autoGenerateDepthImages;
    }

    public void setAutoGenerateDepthImages(boolean autoGenerateDepthImages) {
        this.autoGenerateDepthImages = autoGenerateDepthImages;
    }

    public List<VulkanImage> getColorAttachments() {
        return colorAttachments;
    }

    public void setColorAttachments(List<VulkanImage> colorAttachments) {
        this.colorAttachments = colorAttachments;
    }

    public List<VulkanImage> getDepthAttachments() {
        return depthAttachments;
    }

    public void setDepthAttachments(List<VulkanImage> depthAttachments) {
        this.depthAttachments = depthAttachments;
    }

    protected void checkBuilder() throws BuilderNotPopulatedException {
        if(colorAttachments==null || imagePerStepAmount==0){
            throw new BuilderNotPopulatedException("Error, you need to specify color attachments and amount of them for every render pass");
        }
        if(colorAttachments.size()%imagePerStepAmount!=0){
            throw new BuilderNotPopulatedException("Error, the amount of color attachments must be able to be divide by image per step amount!");
        }
        if(!autoGenerateDepthImages && depthAttachments==null){
            throw new BuilderNotPopulatedException("Error: you specified support for custom depth images, but doesn't specified the images");
        }
        if(depthAttachments!=null && autoGenerateDepthImages){
            System.err.println("Warning, you specified the custom depth images, but does not include support for them!");
        }
    }
}
